INFINITY macro usage changed to std::numeric_limits<float>::infinity() to address warnings in recent Windows SDKs (error C4756: overflow in constant arithmetic)
#rb steve.robb

[CL 35209642 by stefan boberg in ue5-main branch]