Remove redundant pragma causing build error
error: #pragma once in main file [-Werror,-Wpragma-once-outside-header]

#jira UE-136679
#rb Jimmy.Andrews
#lockdown mitchell.wilson

[CL 18386882 by Brandon Schaefer in 4.27-Chaos branch]