Fix TInstancedStruct assignment so Base = Derived assignments work
Without this errors are generated:
error C2446: '!=': no conversion from 'TInstancedStruct<FDerived> *' to 'TInstancedStruct<FBase> *'

With code like:
TInstancedStruct<FBase> Base;
TInstancedStruct<FDerived> Derived;
Base = Derived;   // Error C2446

FInstancedStruct::operator= already guards against assignment with this so this check is largely redundant anyway.
#rb mikko.mononen

[CL 32970638 by thomas sarkanen in ue5-main branch]